#!/bin/sh
# This script's purpose is just to
# automatically compile the kernel
rm -rf /minix/*

if [ `tty` != /dev/console ]
then 
    echo "Wrong terminal, exiting"
    exit 0
fi

cd /usr/src/tools
make hdboot

cd /usr/src
make libraries
make all
make install

cp /usr/bin/getty.old /usr/bin/getty

halt
